// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pojadwyrtxiikljzibdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvamFkd3lydHhpaWtsanppYmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTI1ODksImV4cCI6MjA2NDA4ODU4OX0.9Dd_c8xn6vkkgxS81n-RRAglnl1q96Coi6qimXTBqv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);