
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnawcbjtafsoacqvmyup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduYXdjYmp0YWZzb2FjcXZteXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzM5NTcsImV4cCI6MjA2NzEwOTk1N30.19j5hb2FWloO1Ztku9Dy_UYsEcXogYt6QJdE5_9f7ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
